### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by dopm**
I think you will not like these changes, but this is just for readability

### CODE REVIEW

**Comment by insin** [comment]
It's got a certain something - might need a few tweaks, but thanks!

**Comment by sethkinast** [comment]
I've been using this version as my daily driver but the 18px headings really destroyed scanability for me, so I had to stop using it. Just a data point.

**Comment by insin** [comment]
I might add some settings spinners for title font size and spacing. I really like the larger/space version on the TV/Wii U, but I think I prefer the old style on a desktop.

**Comment by dopm** [comment]
@sethkinast I know it will be different for each person, I see it's easy to read and distinguish each title. It would be very wise to use the old version rather than leaving it. Just point.

**Comment by insin** [comment]
You can now tweak these in settings:

react-hn-117

**Comment by dopm** [comment]
Thank you! a wise middle way

**Pull request merged**
